import{i as N,a as x,S as z,N as D,P as K,K as R,A as F}from"./assets/vendor-DAtLxqiX.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))r(o);new MutationObserver(o=>{for(const a of o)if(a.type==="childList")for(const L of a.addedNodes)L.tagName==="LINK"&&L.rel==="modulepreload"&&r(L)}).observe(document,{childList:!0,subtree:!0});function s(o){const a={};return o.integrity&&(a.integrity=o.integrity),o.referrerPolicy&&(a.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?a.credentials="include":o.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function r(o){if(o.ep)return;o.ep=!0;const a=s(o);fetch(o.href,a)}})();const n={ctgsList:document.querySelector(".pets-ctgs-list"),petsList:document.querySelector(".pets-list"),petsLoadBtn:document.querySelector(".pets-load-btn"),petsLoader:document.querySelector(".pets-loader"),petsPagination:document.querySelector(".pets-pagination")},V=document.querySelector(".burger-btn"),b=document.querySelector(".mobile-menu");document.querySelector(".mobile-menu-btn");document.querySelector(".mobile-menu-container");const U=document.querySelectorAll(".mobile-menu-nav-link, .mobile-menu-button"),M=document.querySelector(".mobile-burger-menu-top-line"),B=document.querySelector(".mobile-burger-menu-mid-line"),A=document.querySelector(".mobile-burger-menu-bot-line"),_=document.querySelector(".header"),C=e=>{e.key==="Escape"&&y()},G=()=>{M.classList.toggle("top-line"),B.classList.toggle("mid-line"),A.classList.toggle("bot-line")},J=()=>{M.classList.remove("top-line"),B.classList.remove("mid-line"),A.classList.remove("bot-line")},Q=()=>{document.body.style.overflow="hidden",document.addEventListener("keydown",C),b.classList.toggle("is-open"),b.className!=="mobile-menu is-open"&&(document.body.style.overflow=""),G()},y=()=>{document.body.style.overflow="",b.classList.remove("is-open"),document.removeEventListener("keydown",C),J()},X=e=>{e.target.closest(".mobile-menu-btn, .mobile-menu-nav-link, .mobile-menu-button")||y()},Y=e=>{e.target.closest(".header-logo, .burger-btn")||y()};V.addEventListener("click",Q);_.addEventListener("click",Y);b.addEventListener("click",X);U.forEach(e=>{e.addEventListener("click",y)});window.addEventListener("resize",()=>{innerWidth>=1440&&(document.body.style.overflow="",b.classList.remove("is-open"),y())});const T=()=>window.innerWidth<768?"mobile":window.innerWidth<1440?"tablet":"desktop",I=()=>g==="mobile"||g==="tablet"?8:9;let m,i=1,p,g=T(),l=I();const f=()=>g==="mobile",O=e=>N.show({message:`Error: ${e}`,position:"topRight",color:"red",close:!1});function w(){const e=Math.ceil(p/l);if(e<=1)return;let t="";if(t+=`<li>
      <button class="pagination-btn-arrow" data-action="prev" aria-label="Попередня сторінка" ${i===1?"disabled":""}><svg class="arrow-icon" width="24" height="24">
          <use href="/img/sprite.svg#icon-arrow-back"></use>
        </svg>
      </button>
    </li>`,i===1){for(let s=1;s<=Math.min(3,e);s++)t+=d(s);e>3&&(t+='<li class="dots">…</li>',t+=d(e))}else if(i===e){t+=d(1),e>3&&(t+='<li class="dots">…</li>');for(let s=e-2;s<=e;s++)s>1&&(t+=d(s))}else{t+=d(1),i>3&&(t+='<li class="dots">…</li>');for(let s=i-1;s<=i+1;s+=1)s>1&&s<e&&(t+=d(s));i<e-2&&(t+='<li class="dots">…</li>'),e>1&&(t+=d(e))}t+=`<li>
      <button class="pagination-btn-arrow" data-action="next" aria-label="Наступна сторінка" ${i===e?"disabled":""}> <svg class="arrow-icon" width="24" height="24">
          <use href="/img/sprite.svg#icon-arrow-forward"></use>
        </svg>
      </button>
    </li>`,n.petsPagination.style.display="flex",n.petsPagination.innerHTML=t}function d(e){return`
    <li>
      <button
        class="pagination-btn ${i===e?"active":""}"
        aria-label="Сторінка ${e}"
        data-page="${e}">
        ${e}
      </button>
    </li>
  `}const Z=async e=>{const t=e.target.closest("button");if(!t)return;const s=Math.ceil(p/l);t.dataset.action==="prev"&&i>1&&(i-=1),t.dataset.action==="next"&&i<s&&(i+=1),t.dataset.page&&(i=+t.dataset.page),h(),E(),await v(i,m),w()};n.petsPagination.addEventListener("click",Z);const ee=async()=>await x("https://paw-hut.b.goit.study/api/categories"),te=e=>{e.unshift({name:"Всі"});const t=["Всі","Собаки","Коти","Кролики","Гризуни","Птахи","Тварини з особливими потребами","Терміново шукають дім"];return e.sort((s,r)=>t.indexOf(s.name)-t.indexOf(r.name)),e.map(s=>`<li class="pets-ctgs-item"><button class="pets-ctgs-btn" aria-pressed="false" data-id="${s._id}" type="button">${s.name}</button></li>`).join("")},se=async()=>{try{const e=await ee();n.ctgsList.innerHTML=te(e.data);const t=document.querySelector(".pets-ctgs-btn");t.classList.add("active"),t.dataset.id="all",t.setAttribute("aria-pressed","true")}catch(e){O(e.message)}},ie=async(e,t)=>{const s={page:e,limit:l};return t&&(s.categoryId=t),await x("https://paw-hut.b.goit.study/api/animals",{params:s})},k=e=>e.map(t=>`<li class="pets-item" role="listitem">
    <img class="pets-img" src="${t.image}" alt="${t.species}">
    <p class="pets-species">${t.species}</p>
    <h3 class="pets-name">${t.name}</h3>
    <ul class="pets-own-ctgs-list">${t.categories.map(s=>`<li class="pets-own-ctgs-item"><p>${s.name}</p></li>`).join("")}</ul>
    <ul class="pets-info">
    <li><p>${t.age}</p></li>
    <li><p>${t.gender}</p></li>
    </ul>
    <p class="pets-short-desc">${t.shortDescription}</p>
    <button class="pets-modal-btn" type="submit">Дізнатись більше</button>
</li>`).join(""),v=async(e,t)=>{try{ce();const s=await ie(e,t);re(),f()?n.petsList.insertAdjacentHTML("beforeend",k(s.data.animals)):n.petsList.innerHTML=k(s.data.animals),p=s.data.totalItems}catch(s){O(s.message)}},h=()=>n.petsList.innerHTML="",oe=e=>{document.querySelectorAll(".pets-ctgs-btn").forEach(s=>{s.classList.remove("active"),s.setAttribute("aria-pressed","false")}),e.classList.add("active"),e.setAttribute("aria-pressed","true")},ne=async e=>{e.target.nodeName==="BUTTON"&&(S(),E(),oe(e.target),m=e.target.dataset.id==="all"?void 0:e.target.dataset.id,i=1,h(),await v(i,m),f()&&p>l?$():f()||w())};n.ctgsList.addEventListener("click",ne);const ae=async()=>{i++,await v(i,m),i*l>=p&&S()};n.petsLoadBtn.addEventListener("click",ae);const S=()=>{n.petsLoadBtn.style.display="none"},$=()=>{n.petsLoadBtn.style.display="block"},re=()=>{n.petsLoader.style.display="none"},ce=()=>{n.petsLoader.style.display="block"},E=()=>{n.petsPagination.style.display="none"},le=()=>{const e=T();e!==g&&(h(),S(),E(),g=e,l=I(),i=1,v(i,m),e==="mobile"&&i*l<p?$():e!=="mobile"&&w())};window.addEventListener("resize",le);const de=async()=>{await se(),await v(i),f()&&p>l?$():f()||w()};de();const q=document.querySelector(".about-swiper-button-next"),P=document.querySelector(".about-swiper-button-prev"),ue=[{id:1,description:"Все почалося у 2015 році з кількох небайдужих людей та одного врятованого собаки. Сьогодні ми — один з найбільших притулків у регіоні, але наша мета незмінна: дати другий шанс тим, кого зрадили."},{id:2,description:'Ми рятуємо, реабілітуємо та знаходимо люблячі родини для безпритульних тварин. Наша мета — не просто дати прихисток, а й забезпечити кожному "хвостику" щасливе та повноцінне життя в новій родині.'},{id:3,description:'"Хатинка Лапок" — це команда професійних ветеринарів, кінологів та десятків волонтерів, які щодня вкладають свою душу та час у турботу про наших підопічних. Ми працюємо 24/7, бо їхнє життя залежить від нас.'},{id:4,description:"Ми створили безпечний та комфортний простір. Кожна тварина отримує якісне харчування, своєчасну ветеринарну допомогу, проходить соціалізацію та гуляє на спеціально обладнаних майданчиках."},{id:5,description:"Ваша допомога — безцінна. Ви можете взяти тваринку додому, стати волонтером, допомогти фінансово або інформаційно. Кожен маленький внесок наближає нас до великої мети — світу без безпритульних тварин."}],u="/project-10/",pe=ue.map(({id:e,description:t})=>`<div class="swiper-slide about-slide">
          <picture>
            <source
              media="(min-width: 1440px)"
              srcset="${u}about-us/desktop/slide-p${e}-desk.webp 1x, ${u}about-us/desktop/slide-p${e}-desk@2x.webp 2x">
            <source
              media="(min-width: 768px)"
              srcset="${u}about-us/tablet/slide-p${e}-tab.webp 1x, ${u}about-us/tablet/slide-p${e}-tab@2x.webp 2x">
            <source
              media="(max-width: 767px)"
              srcset="${u}about-us/mobile/slide-p${e}-mob.webp 1x, ${u}about-us/mobile/slide-p${e}-mob@2x.webp 2x">
            <img 
              class="about-picture"
              src="${u}about-us/mobile/slide-p${e}-mob.webp"
              alt="slide"/>
          </picture>
          <div class="about-overlay">
          <p class="about-id">${t}</p>
          </div>
        </div>`).join("");document.querySelector(".about-swiper-wrapper").innerHTML=pe;const c=new z(".about-mySwiper",{modules:[D,K,R],loop:!1,slidesPerView:1,spaceBetween:10,keyboard:{enabled:!0},pagination:{el:".about .swiper-pagination",clickable:!0},navigation:{nextEl:".about-swiper-button-next",prevEl:".about-swiper-button-prev"}});function W(){const e=document.querySelector(".about .swiper-pagination");window.innerWidth<768?(e.classList.remove("center"),e.classList.add("left")):(e.classList.remove("left"),e.classList.add("center"))}W();window.addEventListener("resize",W);const H=()=>{c.isEnd?q.classList.add("about-btn-disabled"):q.classList.remove("about-btn-disabled"),c.isBeginning?P.classList.add("about-btn-disabled"):P.classList.remove("about-btn-disabled")};c.on("slideChange",H);H();const j=document.querySelector(".about");c.on("slideChangeTransitionStart",()=>{j&&(document.querySelectorAll(".about-id").forEach(e=>e.classList.remove("show")),document.querySelectorAll(".about-overlay").forEach(e=>e.classList.remove("fade-out")))});c.on("slideChangeTransitionEnd",()=>{const e=c.slides[c.activeIndex],t=e.querySelector(".about-id");t&&t.classList.add("show");const s=e.querySelector(".about-overlay");s&&s.classList.add("fade-out")});const be=new IntersectionObserver(e=>{e.forEach(t=>{if(t.isIntersecting){const s=c.slides[c.activeIndex],r=s.querySelector(".about-id"),o=s.querySelector(".about-overlay");r&&(r.classList.remove("show"),r.offsetWidth,r.classList.add("show")),o&&(o.classList.remove("fade-out"),o.offsetWidth,o.classList.add("fade-out"))}})},{threshold:.7});be.observe(j);document.addEventListener("DOMContentLoaded",()=>{new F(".accordion-container",{duration:250,showMultiple:!1,collapse:!0,ariaEnabled:!0})});document.addEventListener("click",e=>{const t=e.target.closest(".ac-trigger");t&&setTimeout(()=>{window.innerWidth<375&&t.scrollIntoView({behavior:"smooth",block:"start"})},450)});
//# sourceMappingURL=index.js.map
